name: Airflow Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_airflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add Helm Repo
      run: |
        helm repo add apache-airflow https://airflow.apache.org
        helm repo update
        
    - name: Connection with Kubernetes cluster
      run: |
        mkdir -p ${{ runner.workspace }}/.kube
        kubectl config view --raw > ${{ runner.workspace }}/.kube/config


    - name: Upgrade Airflow
      run: |
        helm upgrade airflow apache-airflow/airflow -f values.yaml --debug

    - name: Port Forwarding
      run: |
        kubectl port-forward svc/airflow-webserver 9090:9090 &
        sleep 10
        curl http://localhost:9090
